Added Gilded Mechafrog pet, dragonflight, 10.0.7
WowRarity/Rarity pull request #544
Opened 2023-03-28 13:43 UTC by cyriun

forbidden reach map id addition might be a duplicate

2023-03-28 14:06 UTC, cyriun commented
i just click mark as resolved on these right because i think it auto resolves them?

2023-03-28 20:53 UTC, Duckwhale commented
> i just click mark as resolved on these right because i think it auto resolves them?

In this case, the change is already merged (as part of the other PR). Your local branch just doesn't have it yet.

You can update the branch by doing a rebase after updating your local `master`:

![image](https://user-images.githubusercontent.com/16489133/228360898-05fddad5-f8d9-4a95-892e-e6472e247ea7.png)

Then you can simply replay the changes from master on top of the branch (there may be conflicts to resolve):

![image](https://user-images.githubusercontent.com/16489133/228361755-b60866de-7d32-4d0d-8dde-16d933587e9c.png)

In this case, there's two conflicts. Let me know if you want me to sort that out, otherwise I'll let you try the above first :)

2023-03-28 20:57 UTC, Duckwhale requested changes
Should be ready to merge after a rebase, except for the typo I guess 🚀

2023-03-28 20:57 UTC, Duckwhale commented on DB/Pets/Dragonflight.lua
> +		sourceText = L["Inside Zakera Vault Collect Neltharion Gift Tokens to hand in to Prototype Tinker-Tron to recieve Tattered Gift Package which can drop the Gilded Mechafrog"],
Typo: receive

2023-03-28 20:57 UTC, Duckwhale commented on Locales.lua
> +L["Inside Zakera Vault Collect Neltharion Gift Tokens to hand in to Prototype Tinker-Tron to recieve Tattered Gift Package which can drop the Gilded Mechafrog"] =
Typo: receive

2023-03-28 20:57 UTC, Duckwhale commented on DB/SharedConstants.lua
> +	THE_FORBIDDEN_REACH = 2151,
This should go away automatically after a rebase, since the diff from the updated `master` would be empty.

2023-03-29 02:17 UTC, cyriun commented
ok should be good now, i also removed "Bonesifter Marwak" because that was the same case as the duplicate map id

2023-03-29 08:50 UTC, Duckwhale commented
> ok should be good now, i also removed "Bonesifter Marwak" because that was the same case as the duplicate map id

It looks like you performed a merge instead of a rebase. That makes it difficult to work with locally (can't rebase, squash or reorder), and it also branches off in the history. Finally, it keeps the original (redundant) changes around and simply undoes them afterwards. In this case it's probably not useful, so if you don't mind we can undo that and do a proper rebase (as pictured in the screenshots)?

See also https://git-scm.com/book/en/v2/Git-Branching-Rebasing and https://www.atlassian.com/git/tutorials/merging-vs-rebasing

2023-03-29 10:42 UTC, cyriun commented
yeah im not too sure what happened. So i just revert these two?

![chrome_S2CO0ZylDg](https://user-images.githubusercontent.com/124485443/228509227-a504443d-de7e-42f3-8dac-53f6fcab4c87.png)

2023-03-30 00:19 UTC, Duckwhale commented
> yeah im not too sure what happened. So i just revert these two?
> 
> ![chrome_S2CO0ZylDg](https://user-images.githubusercontent.com/124485443/228509227-a504443d-de7e-42f3-8dac-53f6fcab4c87.png)

You can "undo" merge commits, then do the rebase workflow outlined above ;) Let me know if it isn't working!

2023-03-30 03:31 UTC, cyriun commented
ok i think that should have worked, if it didnt, i dont even know anymore haha

2023-03-30 05:06 UTC, Duckwhale commented
> ok i think that should have worked, if it didnt, i dont even know anymore haha

Sorry, my bad. I didn't mean revert (which creates a new commit that undoes the selected changes), but "undo" in GitHub Desktop:

![image](https://user-images.githubusercontent.com/16489133/228734753-460cf05b-bbd5-4a01-a544-c3c20880f5cf.png)

This would remove the merge commits entirely, allowing you to do the rebase. Also check the list of commits, it still has the merges.

2023-03-30 06:27 UTC, cyriun commented
gotcha and yeah i cannot see undo anywhere so i hit revert thinking it was the same thing haha

2023-03-30 07:31 UTC, Duckwhale approved these changes

2023-03-30 07:31 UTC, merged